// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cloudscribe.SimpleContent.Storage.EFCore.PostgreSql;

#nullable disable

namespace cloudscribe.SimpleContent.Storage.EFCore.PostgreSql.Migrations
{
    [DbContext(typeof(SimpleContentDbContext))]
    [Migration("20240918132310_ShowArchiveAndBlogCategories-20240918")]
    partial class ShowArchiveAndBlogCategories20240918
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cloudscribe.SimpleContent.Models.ContentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArchivedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("archived_by");

                    b.Property<DateTime>("ArchivedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_utc");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author");

                    b.Property<string>("CategoriesCsv")
                        .HasColumnType("text")
                        .HasColumnName("categories_csv");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("content_id");

                    b.Property<string>("ContentSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content_source");

                    b.Property<string>("ContentType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("html")
                        .HasColumnName("content_type");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("correlation_key");

                    b.Property<string>("CreatedByUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_user");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("DraftAuthor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("draft_author");

                    b.Property<string>("DraftContent")
                        .HasColumnType("text")
                        .HasColumnName("draft_content");

                    b.Property<DateTime?>("DraftPubDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("draft_pub_date");

                    b.Property<string>("DraftSerializedModel")
                        .HasColumnType("text")
                        .HasColumnName("draft_serialized_model");

                    b.Property<bool>("IsDraftHx")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draft_hx");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedByUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_modified_by_user");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("text")
                        .HasColumnName("meta_description");

                    b.Property<string>("MetaHtml")
                        .HasColumnType("text")
                        .HasColumnName("meta_html");

                    b.Property<string>("MetaJson")
                        .HasColumnType("text")
                        .HasColumnName("meta_json");

                    b.Property<int>("PageOrder")
                        .HasColumnType("integer")
                        .HasColumnName("page_order");

                    b.Property<string>("ParentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentSlug")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("parent_slug");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("PubDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pub_date");

                    b.Property<string>("SerializedModel")
                        .HasColumnType("text")
                        .HasColumnName("serialized_model");

                    b.Property<string>("Serializer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serializer");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<string>("TeaserOverride")
                        .HasColumnType("text")
                        .HasColumnName("teaser_override");

                    b.Property<string>("TemplateKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("template_key");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("ViewRoles")
                        .HasColumnType("text")
                        .HasColumnName("view_roles");

                    b.Property<bool>("WasDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("was_deleted");

                    b.HasKey("Id")
                        .HasName("pk_cs_content_history");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("ix_cs_content_history_content_id");

                    b.HasIndex("ContentSource")
                        .HasDatabaseName("ix_cs_content_history_content_source");

                    b.HasIndex("CorrelationKey")
                        .HasDatabaseName("ix_cs_content_history_correlation_key");

                    b.HasIndex("CreatedByUser")
                        .HasDatabaseName("ix_cs_content_history_created_by_user");

                    b.HasIndex("LastModifiedByUser")
                        .HasDatabaseName("ix_cs_content_history_last_modified_by_user");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_cs_content_history_title");

                    b.ToTable("cs_content_history", (string)null);
                });

            modelBuilder.Entity("cloudscribe.SimpleContent.Models.ProjectSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AboutContent")
                        .HasColumnType("text")
                        .HasColumnName("about_content");

                    b.Property<string>("AboutHeading")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("about_heading");

                    b.Property<bool>("AddBlogToPagesTree")
                        .HasColumnType("boolean")
                        .HasColumnName("add_blog_to_pages_tree");

                    b.Property<bool>("BlogMenuLinksToNewestPost")
                        .HasColumnType("boolean")
                        .HasColumnName("blog_menu_links_to_newest_post");

                    b.Property<string>("BlogPageNavComponentVisibility")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("blog_page_nav_component_visibility");

                    b.Property<int>("BlogPagePosition")
                        .HasColumnType("integer")
                        .HasColumnName("blog_page_position");

                    b.Property<string>("BlogPageText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("blog_page_text");

                    b.Property<string>("CdnUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cdn_url");

                    b.Property<string>("ChannelCategoriesCsv")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("channel_categories_csv");

                    b.Property<string>("ChannelRating")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("channel_rating");

                    b.Property<int>("ChannelTimeToLive")
                        .HasColumnType("integer")
                        .HasColumnName("channel_time_to_live");

                    b.Property<string>("CommentNotificationEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("comment_notification_email");

                    b.Property<string>("CopyrightNotice")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("copyright_notice");

                    b.Property<int>("DaysToComment")
                        .HasColumnType("integer")
                        .HasColumnName("days_to_comment");

                    b.Property<string>("DefaultContentType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("html")
                        .HasColumnName("default_content_type");

                    b.Property<int>("DefaultFeedItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("default_feed_items");

                    b.Property<string>("DefaultPageSlug")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("default_page_slug");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisqusShortName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("disqus_short_name");

                    b.Property<string>("FacebookAppId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("facebook_app_id");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image");

                    b.Property<bool>("IncludePubDateInPostUrls")
                        .HasColumnType("boolean")
                        .HasColumnName("include_pub_date_in_post_urls");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("LocalMediaVirtualPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("local_media_virtual_path");

                    b.Property<string>("ManagingEditorEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("managing_editor_email");

                    b.Property<int>("MaxFeedItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000)
                        .HasColumnName("max_feed_items");

                    b.Property<bool>("ModerateComments")
                        .HasColumnType("boolean")
                        .HasColumnName("moderate_comments");

                    b.Property<int>("PostsPerPage")
                        .HasColumnType("integer")
                        .HasColumnName("posts_per_page");

                    b.Property<string>("PubDateFormat")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("pub_date_format");

                    b.Property<string>("Publisher")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("publisher");

                    b.Property<string>("PublisherEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("publisher_entity_type");

                    b.Property<string>("PublisherLogoHeight")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("publisher_logo_height");

                    b.Property<string>("PublisherLogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("publisher_logo_url");

                    b.Property<string>("PublisherLogoWidth")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("publisher_logo_width");

                    b.Property<string>("RecaptchaPrivateKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recaptcha_private_key");

                    b.Property<string>("RecaptchaPublicKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recaptcha_public_key");

                    b.Property<string>("RemoteFeedProcessorUseAgentFragment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remote_feed_processor_use_agent_fragment");

                    b.Property<string>("RemoteFeedUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remote_feed_url");

                    b.Property<bool>("ShowAboutBox")
                        .HasColumnType("boolean")
                        .HasColumnName("show_about_box");

                    b.Property<bool>("ShowArchivedPosts")
                        .HasColumnType("boolean")
                        .HasColumnName("show_archived_posts");

                    b.Property<bool>("ShowBlogCategories")
                        .HasColumnType("boolean")
                        .HasColumnName("show_blog_categories");

                    b.Property<bool>("ShowFeaturedPostsOnDefaultPage")
                        .HasColumnType("boolean")
                        .HasColumnName("show_featured_posts_on_default_page");

                    b.Property<bool>("ShowRecentPostsOnDefaultPage")
                        .HasColumnType("boolean")
                        .HasColumnName("show_recent_posts_on_default_page");

                    b.Property<bool>("ShowRelatedPosts")
                        .HasColumnType("boolean")
                        .HasColumnName("show_related_posts");

                    b.Property<bool>("ShowTitle")
                        .HasColumnType("boolean")
                        .HasColumnName("show_title");

                    b.Property<string>("SiteName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("site_name");

                    b.Property<byte>("TeaserMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("teaser_mode");

                    b.Property<int>("TeaserTruncationLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("teaser_truncation_length");

                    b.Property<byte>("TeaserTruncationMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("teaser_truncation_mode");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("TwitterCreator")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("twitter_creator");

                    b.Property<string>("TwitterPublisher")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("twitter_publisher");

                    b.Property<bool>("UseDefaultPageAsRootNode")
                        .HasColumnType("boolean")
                        .HasColumnName("use_default_page_as_root_node");

                    b.Property<string>("WebmasterEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("webmaster_email");

                    b.HasKey("Id")
                        .HasName("pk_cs_content_project");

                    b.ToTable("cs_content_project", (string)null);
                });

            modelBuilder.Entity("cloudscribe.SimpleContent.Storage.EFCore.Models.PageCategory", b =>
                {
                    b.Property<string>("Value")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("value");

                    b.Property<string>("PageEntityId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("page_entity_id");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_id");

                    b.HasKey("Value", "PageEntityId")
                        .HasName("pk_cs_page_category");

                    b.HasIndex("PageEntityId")
                        .HasDatabaseName("ix_cs_page_category_page_entity_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_cs_page_category_project_id");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_cs_page_category_value");

                    b.ToTable("cs_page_category", (string)null);
                });

            modelBuilder.Entity("cloudscribe.SimpleContent.Storage.EFCore.Models.PageComment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Ip")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ip");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<string>("PageEntityId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("page_entity_id");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("PubDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pub_date");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_agent");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_cs_page_comment");

                    b.HasIndex("PageEntityId")
                        .HasDatabaseName("ix_cs_page_comment_page_entity_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_cs_page_comment_project_id");

                    b.ToTable("cs_page_comment", (string)null);
                });

            modelBuilder.Entity("cloudscribe.SimpleContent.Storage.EFCore.Models.PageEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author");

                    b.Property<string>("CategoriesCsv")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("categories_csv");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("html")
                        .HasColumnName("content_type");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("correlation_key");

                    b.Property<string>("CreatedByUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_user");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<bool>("DisableEditor")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_editor");

                    b.Property<string>("DraftAuthor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("draft_author");

                    b.Property<string>("DraftContent")
                        .HasColumnType("text")
                        .HasColumnName("draft_content");

                    b.Property<DateTime?>("DraftPubDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("draft_pub_date");

                    b.Property<string>("DraftSerializedModel")
                        .HasColumnType("text")
                        .HasColumnName("draft_serialized_model");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_url");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedByUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_modified_by_user");

                    b.Property<string>("MenuFilters")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("menu_filters");

                    b.Property<bool>("MenuOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("menu_only");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("meta_description");

                    b.Property<string>("MetaHtml")
                        .HasColumnType("text")
                        .HasColumnName("meta_html");

                    b.Property<string>("MetaJson")
                        .HasColumnType("text")
                        .HasColumnName("meta_json");

                    b.Property<int>("PageOrder")
                        .HasColumnType("integer")
                        .HasColumnName("page_order");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentSlug")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("parent_slug");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("PubDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pub_date");

                    b.Property<string>("SerializedModel")
                        .HasColumnType("text")
                        .HasColumnName("serialized_model");

                    b.Property<string>("Serializer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serializer");

                    b.Property<bool>("ShowCategories")
                        .HasColumnType("boolean")
                        .HasColumnName("show_categories");

                    b.Property<bool>("ShowComments")
                        .HasColumnType("boolean")
                        .HasColumnName("show_comments");

                    b.Property<bool>("ShowHeading")
                        .HasColumnType("boolean")
                        .HasColumnName("show_heading");

                    b.Property<bool>("ShowLastModified")
                        .HasColumnType("boolean")
                        .HasColumnName("show_last_modified");

                    b.Property<bool>("ShowMenu")
                        .HasColumnType("boolean")
                        .HasColumnName("show_menu");

                    b.Property<bool>("ShowPubDate")
                        .HasColumnType("boolean")
                        .HasColumnName("show_pub_date");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<string>("TemplateKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("template_key");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("ViewRoles")
                        .HasColumnType("text")
                        .HasColumnName("view_roles");

                    b.HasKey("Id")
                        .HasName("pk_cs_page");

                    b.HasIndex("CorrelationKey")
                        .HasDatabaseName("ix_cs_page_correlation_key");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_cs_page_parent_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_cs_page_project_id");

                    b.ToTable("cs_page", (string)null);
                });

            modelBuilder.Entity("cloudscribe.SimpleContent.Storage.EFCore.Models.PageResourceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("environment");

                    b.Property<string>("PageEntityId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("page_entity_id");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_cs_page_resource");

                    b.HasIndex("PageEntityId")
                        .HasDatabaseName("ix_cs_page_resource_page_entity_id");

                    b.ToTable("cs_page_resource", (string)null);
                });

            modelBuilder.Entity("cloudscribe.SimpleContent.Storage.EFCore.Models.PostCategory", b =>
                {
                    b.Property<string>("Value")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("value");

                    b.Property<string>("PostEntityId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("post_entity_id");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_id");

                    b.HasKey("Value", "PostEntityId")
                        .HasName("pk_cs_post_category");

                    b.HasIndex("PostEntityId")
                        .HasDatabaseName("ix_cs_post_category_post_entity_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_cs_post_category_project_id");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_cs_post_category_value");

                    b.ToTable("cs_post_category", (string)null);
                });

            modelBuilder.Entity("cloudscribe.SimpleContent.Storage.EFCore.Models.PostComment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Ip")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ip");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<string>("PostEntityId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("post_entity_id");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("PubDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pub_date");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_agent");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_cs_post_comment");

                    b.HasIndex("PostEntityId")
                        .HasDatabaseName("ix_cs_post_comment_post_entity_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_cs_post_comment_project_id");

                    b.ToTable("cs_post_comment", (string)null);
                });

            modelBuilder.Entity("cloudscribe.SimpleContent.Storage.EFCore.Models.PostEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author");

                    b.Property<string>("AutoTeaser")
                        .HasColumnType("text")
                        .HasColumnName("auto_teaser");

                    b.Property<string>("BlogId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("blog_id");

                    b.Property<string>("CategoriesCsv")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("categories_csv");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("html")
                        .HasColumnName("content_type");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("correlation_key");

                    b.Property<string>("CreatedByUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_user");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("DraftAuthor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("draft_author");

                    b.Property<string>("DraftContent")
                        .HasColumnType("text")
                        .HasColumnName("draft_content");

                    b.Property<DateTime?>("DraftPubDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("draft_pub_date");

                    b.Property<string>("DraftSerializedModel")
                        .HasColumnType("text")
                        .HasColumnName("draft_serialized_model");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedByUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_modified_by_user");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("meta_description");

                    b.Property<string>("MetaHtml")
                        .HasColumnType("text")
                        .HasColumnName("meta_html");

                    b.Property<string>("MetaJson")
                        .HasColumnType("text")
                        .HasColumnName("meta_json");

                    b.Property<DateTime?>("PubDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pub_date");

                    b.Property<string>("SerializedModel")
                        .HasColumnType("text")
                        .HasColumnName("serialized_model");

                    b.Property<string>("Serializer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serializer");

                    b.Property<bool>("ShowComments")
                        .HasColumnType("boolean")
                        .HasColumnName("show_comments");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<bool>("SuppressTeaser")
                        .HasColumnType("boolean")
                        .HasColumnName("suppress_teaser");

                    b.Property<string>("TeaserOverride")
                        .HasColumnType("text")
                        .HasColumnName("teaser_override");

                    b.Property<string>("TemplateKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("template_key");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_cs_post");

                    b.HasIndex("BlogId")
                        .HasDatabaseName("ix_cs_post_blog_id");

                    b.HasIndex("CorrelationKey")
                        .HasDatabaseName("ix_cs_post_correlation_key");

                    b.HasIndex("Slug")
                        .HasDatabaseName("ix_cs_post_slug");

                    b.ToTable("cs_post", (string)null);
                });

            modelBuilder.Entity("cloudscribe.SimpleContent.Storage.EFCore.Models.PageComment", b =>
                {
                    b.HasOne("cloudscribe.SimpleContent.Storage.EFCore.Models.PageEntity", null)
                        .WithMany("PageComments")
                        .HasForeignKey("PageEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_cs_page_comment_cs_page_page_entity_id");
                });

            modelBuilder.Entity("cloudscribe.SimpleContent.Storage.EFCore.Models.PageResourceEntity", b =>
                {
                    b.HasOne("cloudscribe.SimpleContent.Storage.EFCore.Models.PageEntity", null)
                        .WithMany("PageResources")
                        .HasForeignKey("PageEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_cs_page_resource_cs_page_page_entity_id");
                });

            modelBuilder.Entity("cloudscribe.SimpleContent.Storage.EFCore.Models.PostComment", b =>
                {
                    b.HasOne("cloudscribe.SimpleContent.Storage.EFCore.Models.PostEntity", null)
                        .WithMany("PostComments")
                        .HasForeignKey("PostEntityId")
                        .HasConstraintName("fk_cs_post_comment_cs_post_post_entity_id");
                });

            modelBuilder.Entity("cloudscribe.SimpleContent.Storage.EFCore.Models.PageEntity", b =>
                {
                    b.Navigation("PageComments");

                    b.Navigation("PageResources");
                });

            modelBuilder.Entity("cloudscribe.SimpleContent.Storage.EFCore.Models.PostEntity", b =>
                {
                    b.Navigation("PostComments");
                });
#pragma warning restore 612, 618
        }
    }
}
